service: lifeworks-tech-test

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    # In a real app should import this url from an env file.
    BASE_URL: 'https://apigateway.test.lifeworks.com/rescue-shelter-api'

functions:
  adoptions:
    handler: handlers/list-adoptions.handler
    events:
     - http:
         path: /adoptions
         method: get
