service: lifeworks-tech-test

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    BASE_URL: ${file(env.yml):BASE_API_URL}

functions:
  adoptions:
    handler: handlers/list-adoptions.handler
    events:
     - http:
         path: /adoptions
         method: get
